author: Melinda Higgins, Ph.D.
description: My website and blog
permalink: /blog/:categories/:year/:month/:day/:title.html
url: http://melindahiggins2000.github.io/web2
baseurl: http://melindahiggins2000.github.io
gems: [jekyll-feed]
exclude: ["Rmd", ".DS_Store", "README.md"]
excerpt_separator: <!--more-->
